### ISSUE TITLE
Searching can be quite slow

### ISSUE THREAD

**Issue by herronelou** [dbr/shortcuteditor-nuke#11]
It looks like the table is mostly rebuilt from scratch when searching through the keyboard shortcuts.
This leads to some consequent slowdowns when searching.
I recently encountered a similar issue on another tool, which was solved by using a QSortFilterProxyModel to do filtering rather than rebuilding from scratch.
Another advantage would be that each menu entry would now have a fixed index in the table, which would allow easier referencing from one to the other (for example in merge request #10 I couldn't efficiently refresh the widget when overriding a shortcut without possibly iterating over every widget).

Maybe I will try an implementation, though it is a consequent change.

**Comment by dbr** [comment]
Closing, some kind person fixed this for you in PR #12.. :D
