### ISSUE TITLE
Not working correctly in Nuke 11.2v4

### ISSUE THREAD

**Issue by Apocalypse612** [dbr/shortcuteditor-nuke#9]
All of the keyboard shortcuts show up as blank from the menu, and when you go to change / clear the shortcuts, nothing happens. 

![2018-11-03_12-12-52](https://user-images.githubusercontent.com/6374154/47956442-d0a38800-df61-11e8-95d1-6823cbbbe425.jpg)

**Comment by dbr** [comment]
Hmm this seems to be a bug with Nuke - the method the UI uses to get the existing shortcut always returns a blank string:

```python
print nuke.menu("Nodes").findItem("Image/Read").shortcut()
```
..currently returns an empty string when it should return "r"

Still broken with 12.1v4 - I'll report this to Foundry

**Comment by dbr** [comment]
Reported, shall update with bug number when confirmed

**Comment by dbr** [comment]
Is [bug 138884](https://support.foundry.com/hc/en-us/articles/360015797060-ID-138884-nuke-menu-Nodes-findItem-Menu-Node-shortcut-returns-an-empty-string-on-Windows)

However there is a decent workaround - using `nuke.menu("Nodes").findItem("Image/Read").action().shortcut()`

There's also a bunch of stuff not working with the shortcut-capture widget either on Windows or in newer Qt that I'll fix up

**Comment by Apocalypse612** [comment]
Thank you!

**Comment by dbr** [comment]
Should all be working again in newly released v1.2
